### ISSUE TITLE
Not calculating position correctly

### ISSUE THREAD

**Issue by phiychai** [Financial-Times/o-tooltip#94] opened 2020-02-10 16:27 UTC
## What

Tooltip content position is not calculated correctly

## Details

- describe the environment you are having this problem in
	- Win 10 (Edge latest)
         Win 10 (IE11)
	- iPhone XS (IOS 13) Safari

**Chrome latest (how it should look)**
![image](https://user-images.githubusercontent.com/3500928/74168581-4220ba80-4c2a-11ea-9b10-52eb45b6ba6f.png)

**Edge latest (appears at top of page)**
![image](https://user-images.githubusercontent.com/3500928/74168706-68465a80-4c2a-11ea-9abf-296ed4200b24.png)

**Comment by notlee** [comment] 2020-02-13 10:39
Hi @bbcreatv, have you been able to work around this issue? Just trying to prioritise incoming issues 😊 Also to help us debug this:
- are you using the "append to body" option?
- is there a page we can preview this?

**Comment by notlee** [comment] 2020-02-17 16:32
Hmm I've only been able to reproduce this for Edge 18. Not Edge 80, IE11, or IOS 13. Are you still seeing this in those browsers @bbcreatv?

Edge 18 is not good:
<img width="473" alt="windows-10-edge-18" src="https://user-images.githubusercontent.com/10405691/74671363-e95d9e80-51a2-11ea-82ef-08561bd122d1.png">

IE11 seems ok:
<img width="500" alt="windows-10-ie-11" src="https://user-images.githubusercontent.com/10405691/74671365-e9f63500-51a2-11ea-9c08-9eafb5239b57.png">

Edge 80 seems ok:
<img width="487" alt="windows-10-edge-80" src="https://user-images.githubusercontent.com/10405691/74671364-e95d9e80-51a2-11ea-8db6-0855bb3019ad.png">

IOS 13 seems ok:
<img width="407" alt="iphone-xs-ios-13" src="https://user-images.githubusercontent.com/10405691/74671362-e8c50800-51a2-11ea-918b-cfdf3b171695.png">

**Comment by bbcreatv** [comment] 2020-02-18 09:13
Sorry @notlee it seems to be visible only on Edge 18, not IE11. It was Edge latest on BS up until last week and 80 was Beta. And its visible on iPhone 6 (IOS 11) not XS

**Comment by chee** [comment] 2021-08-13 12:32
going to close this :)

looks like it only happens on a browser we don't support (edge 18)

**Closed by chee** 2021-08-13 12:32 UTC
Labels: bug, component
